### ISSUE TITLE
Don't offer flavours that don't work with our default image

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#109] opened 2017-11-30 15:30 UTC
A tech preview customer selected `m1.small` and the creation fails with a rather generic error `Couldn't create node k8s-pool-test-fqt2v: Invalid request due to incorrect syntax or missing required parameters.`.
Digging through the nova logs I found `Flavor's memory is too small for requested image`. We should avoid giving the users a selection that is bound to fail.

We need to decide where we want to fix it, the openstack metadata call or the UI.

**Comment by BugRoger** [comment] 2017-11-30 18:12
Hm. Odd. Small used to work

**Comment by edda** [comment] 2017-12-04 09:49
I always use small. So far haven't had an issue with it.

**Comment by bozinsky** [comment] 2017-12-04 09:51
I have fixed the small image issue. Was caused by a external constraint in openstack. You can close this.

**Comment by BugRoger** [comment] 2017-12-04 10:08
We now collect the flavors from Openstack.  If the UI picks the flavors from the `metadata` API, we could filter the list to only return working flavors.

Would also be good to have for custom flavors. O other Openstacks with different naming schemes...

**Comment by BugRoger** [comment] 2018-01-02 16:13
Fixed by #130?

**Comment by BugRoger** [comment] 2018-01-03 10:04
Fixed by #130

**Closed by BugRoger** 2018-01-03 10:04 UTC
Labels: enhancement
